'use client';

import '../styles/globals.scss';
import type { Metadata } from 'next';
import Header from '../components/header';
import { ReduxProvider } from '@/redux/provider';
import Aside from '../components/aside';
import Search from '../components/search';

export const metadata: Metadata = {
   title: 'Timesprint',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body>
            <ReduxProvider>
               <Search />
               <Header />
               <Aside />
               {children}
            </ReduxProvider>
         </body>
      </html>
   );
}
